# Generated by Django 4.1.5 on 2023-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.IntegerField(default=100),
        ),
    ]
