# Generated by Django 4.2 on 2023-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.IntegerField(default=3500),
        ),
    ]
